apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: result-app-deploy
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result-app-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
