apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: my-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: postgres-pod
      app: my-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: my-voting-app

    spec:
      containers:
      - name: postgres
        image: docker-registry.local.com:5000/postgres:9.4
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: mydockercred

