apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: my-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: my-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: my-voting-app

    spec:
      containers:
      - name: result-app
        image: docker-registry.local.com:5000/votingapp_result:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mydockercred  